<?php

use App\Http\Controllers\AuxiliaryAppController;
use App\Http\Controllers\CampaignController;
use App\Http\Controllers\CommercialConditionController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\OtherSettingController;
use App\Http\Controllers\PerformanceReportController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RegionController;
use App\Http\Controllers\SalesIntelligenceController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Controllers\TenantFeedbackEntryController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VisitController;
use Illuminate\Support\Facades\Route;

Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
Route::get('/dashboard/export', [DashboardController::class, 'export'])->name('dashboard.export');
Route::get('/reports/sales', [PerformanceReportController::class, 'sales'])->name('reports.sales');
Route::get('/reports/sellers', [PerformanceReportController::class, 'sellers'])->name('reports.sellers');
Route::get('/subscription', [SubscriptionController::class, 'index'])->name('subscription.index');
Route::patch('/subscription', [SubscriptionController::class, 'update'])->name('subscription.update');
Route::post('/subscription/pix', [PaymentController::class, 'generatePix'])->name('subscription.pix');
Route::get('/subscription/payments/{paymentId}', [PaymentController::class, 'status'])->name('subscription.payment-status');
Route::get('/company', [CompanyController::class, 'index'])->name('company.index');
Route::patch('/company', [CompanyController::class, 'update'])->name('company.update');
Route::get('/other-settings', [OtherSettingController::class, 'index'])->name('other-settings.index');
Route::get('/auxiliary-apps', [AuxiliaryAppController::class, 'index'])->name('auxiliary-apps.index');
Route::get('/feedback', [TenantFeedbackEntryController::class, 'index'])->name('feedback.index');
Route::post('/feedback', [TenantFeedbackEntryController::class, 'store'])->name('feedback.store');
Route::resource('/customers', CustomerController::class);
Route::resource('/regions', RegionController::class);
Route::resource('/visits', VisitController::class);
Route::resource('/expenses', ExpenseController::class);
Route::patch('/visits/{visit}/check-in', [VisitController::class, 'checkIn'])->name('visits.check-in');
Route::patch('/visits/{visit}/check-out', [VisitController::class, 'checkOut'])->name('visits.check-out');
Route::get('/intelligence', [SalesIntelligenceController::class, 'index'])->name('intelligence.index');
Route::resource('/campaigns', CampaignController::class);
Route::get('/commissions', [CommercialConditionController::class, 'commissions'])->name('commissions.index');
Route::get('/commissions/report', [CommercialConditionController::class, 'commissionReport'])->name('commissions.report');
Route::resource('/commercial-conditions', CommercialConditionController::class);
Route::resource('/orders', OrderController::class);
Route::get('/report', [OrderController::class, 'orderReport'])->name('orders.report');
Route::resource('/products', ProductController::class);
Route::get('/settings', fn () => redirect()->route('app.other-settings.index'))->name('settings.index');
Route::resource('/users', UserController::class);
Route::get('/refproducts/{reference}', [ProductController::class, 'getProductsReference']);
Route::patch('/statusorder/{order}', [OrderController::class, 'setValueStatusOrder']);
Route::patch('/cancelorder/{order}', [OrderController::class, 'cancelOrder']);
